### ISSUE TITLE
[2.0]Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wuzhuzhu** [prisma/prisma-binding#162]
All previous working query down when upgrade prisma-binding to 2.0.0 from 1.5.19.
Err: 
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:54:12
    at step (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:43:10)
    at Prisma.Delegate.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/src/Delegate.ts:154:20)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:54:12
    at step (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:43:10)
    at Prisma.Delegate.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/src/Delegate.ts:154:20)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:54:12
    at step (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:43:10)
    at Prisma.Delegate.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/src/Delegate.ts:154:20)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:54:12
    at step (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:43:10)
    at Prisma.Delegate.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/src/Delegate.ts:154:20)
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:54:12
    at step (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)
    at Object.next (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)
    at /Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:12)
    at delegateToSchemaImplementation (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:57:12)
    at Object.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:43:10)
    at Prisma.Delegate.delegateToSchema (/Users/someone/SomeProject/Projectname/server/node_modules/graphql-binding/src/Delegate.ts:154:2
```

**Comment by schickling** [comment]
Thanks a lot for reporting this @wuzhuzhu! Can you please provide a minimal reproduction repo? We'll look into this asap!

**Comment by overpod** [comment]
**Here it is possible to reproduce**
https://github.com/graphql-boilerplates/typescript-graphql-server.git

**Comment by timsuchanek** [comment]
@wuzhuzhu @overpod I just tried to reproduce the problem, but couldn't.
Can you share a repo with the exact app & the query you're trying to execute?
Note that you should replace `prepare` with `codegen`.
Here I did the necessary steps to get it running with the basic example & prisma-binding@2:
https://github.com/graphql-boilerplates/typescript-graphql-server/compare/prisma-binding2

You can see the branch here:
https://github.com/graphql-boilerplates/typescript-graphql-server/tree/prisma-binding2/basic

**Comment by kriswep** [comment]
Had the same problem with an typescript-prisma project after upgrading to prisma-binding@2.0.0

Can confirm that switching the config in prisma.yml and .graphqlconfig.yml and running `prisma deploy` fixed it for me.

For reference:
`./database/prisma.yml`
```yml
# endpoint, datamodel, secret and everything else as before...
# only changes in the hooks part

# Download the GraphQL schema of the Prisma API into
# `src/generated/prisma.graphql` (as specfied in `.graphqlconfig.yml`).
# Then generate the corresponding TypeScript definitions into
# `src/generated/prisma.ts` (also specfied in `.graphqlconfig.yml`)
# with `graphql prepare` .
hooks:
  post-deploy:
    - graphql get-schema
    - graphql codegen

```

`./.graphqlconfig.yml`
```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
      codegen:
        output:
          binding: src/generated/prisma.ts
        generator: prisma-binding
        language: typescript
```

**Comment by abelovic** [comment]
@kriswep @timsuchanek - Unfortunately this did not work for me :( The only thing based on this snippet that I have that is different is I am using plain javascript instead of typescript.

I have had issues with the hooks running as well - see here: https://github.com/graphcool/prisma-binding/issues/164 so to make sure the hooks ran (graphql get-schema && graphql codegen) - I put it in my npm script after just to make sure. Still get the same error

**Comment by divyenduz** [comment]
@adamkl : Were you using `yarn link` or `npm link` with `graphql-tools` by any chance, otherwise, you should not have seen that issue? 

Generally, we deployed a [release today](https://github.com/graphql-cli/graphql-cli/releases/tag/v2.16.1) that makes `graphql codegen` more robust. 

Please install the new cli via `npm install -g graphql-cli` and try the `graphql codegen` command. 

Note that with `prisma-binding` 1.x, we need to use `graphql prepare`
and with `prisma-binding` 2.x, we need to use `graphql codegen`

[Documentation for codegen](https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3).

Thanks!

**Comment by harrisrobin** [comment]
Having the same issue and changing from `graphql prepare` to `graphql codgen` did not work.

Here's my package.json:

```json
{
  "name": "entr-server",
  "scripts": {
    "start": "node dist/index.js",
    "start:local": "node -r dotenv/config dist/index.js",
    "start:nodemon": "nodemon -e ts,graphql -x ts-node -r dotenv/config src/index.ts",
    "dev": "npm-run-all --parallel start:nodemon playground",
    "playground": "graphql playground",
    "build": "rm -rf dist && graphql codegen && tsc",
    "deploy:prod": "yarn prisma:login && yarn prisma:deploy:prod && yarn yoga:deploy:prod",
    "prisma:deploy": "prisma deploy",
    "prisma:deploy:prod": "prisma deploy -e .env.prod",
    "prisma:login": "prisma login --key {CENSORED}",
    "prisma:token": "prisma token",
    "prisma:token:prod": "prisma token -e .env.prod",
    "prisma:export:prod": "prisma export --path database/exports/export -e .env.prod",
    "prisma:import": "prisma import --data database/exports/export.zip",
    "yoga:deploy:prod": "yarn build && up deploy production",
    "danger:local:nuke": "prisma local nuke",
    "danger:prod:reset": "prisma reset -e .env.prod",
    "types:generate:flow": "apollo-codegen generate queries/*.graphql --schema schema.json --target flow --output generated-types/operation-result-types.flow.js"
  },
  "dependencies": {
    "accept-language-parser": "^1.5.0",
    "email-templates": "^3.6.0",
    "express-jwt": "^5.3.1",
    "graphql-middleware-sentry": "^1.0.1",
    "graphql-tools": "^3.0.2",
    "graphql-yoga": "1.14.7",
    "isomorphic-fetch": "^2.2.1",
    "jsonwebtoken": "^8.2.1",
    "jwks-rsa": "^1.2.1",
    "luxon": "^1.2.0",
    "node-fetch": "^2.1.2",
    "prisma-binding": "^2.0.2",
    "ramda": "^0.25.0"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.1",
    "@types/email-templates": "^3.5.0",
    "@types/luxon": "^0.5.2",
    "dotenv": "^5.0.1",
    "graphql-cli": "2.16.2",
    "nodemon": "^1.17.3",
    "npm-run-all": "4.1.2",
    "prisma": "^1.9.0",
    "ts-node": "5.0.1",
    "typescript": "2.8.1"
  },
  "prettier": {
    "semi": false,
    "trailingComma": "all"
  }
}
```

```yml
endpoint: ${env:PRISMA_ENDPOINT}
secret: ${env:PRISMA_MANAGEMENT_API_SECRET}
cluster: ${env:PRISMA_CLUSTER}

datamodel:
- datamodel/types.graphql
- datamodel/enums.graphql

seed:
  import: exports/export.zip

hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project database
    - graphql codegen
```
This is my second try and i reverted back to older versions of these packages.

**Comment by divyenduz** [comment]
@harrisrobin : Can you please share your `.graphqlconfig` file? It should have `codegen` extension for `graphql codegen` command to work as expected. 

Did you already follow the [upgrade guide](https://www.prisma.io/docs/reference/prisma-bindings/code-generation-cosha9rah3#upgrading-from-prisma-binding-v1.x) from 1.x to 2.x?

**Comment by zgababa** [comment]
I have the same problem , when I run a mutation with "prisma-binding": "2.1.1"
```
Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at /Users/fabien/Projects/course/api/node_modules/graphql-binding/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:63:112
```

I followed the upgrade guide, do I need to add this part even if I don't use typescript ? 
```
codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts

```
.graphqlconfig.yml
```
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
```
prisma.yml 
```
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project prisma
    - graphql codegen
```
 And I create with no problem a new prisma.graphql with `prisma deploy`

Thank you,
