### ISSUE TITLE
Duplicate export for `Prisma` Flow generation

### ISSUE THREAD

**Issue by steida** [prisma/prisma-binding#187]
Flow generation is super awesome. I just tried it but got an error: Duplicate export for `Prisma`

```
projects:
  api:
    schemaPath: "server/api/model.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "database/schema.graphql"
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: flow
          output:
            binding: database/types.js
```

```
datamodel: model.graphql

endpoint: ${env:PRISMA_ENDPOINT}

secret: ${env:PRISMA_SECRET}

hooks:
  post-deploy:
    - graphql get-schema --project database
    - graphql codegen
```

![screen shot 2018-06-13 at 22 35 05](https://user-images.githubusercontent.com/66249/41376635-0ae65042-6f5a-11e8-82dd-4749ec06da20.png)

Why it generates both `export interface Prisma {` and `export const Prisma: BindingConstructor<Prisma> = makePrismaBindingClass({typeDefs})`? What am I doing wrong?
